### ISSUE TITLE
Error generating CSV from Discover screen (Failed to generate report: TypeError: Cannot read property 'settings' of undefined)

### ISSUE THREAD

**Issue by gsmith-sas** [opendistro-for-elasticsearch/kibana-reports#251]
I have deployed ODFE 1.12.0 into my Kubernetes cluster using the Helm chart.  Elasticsearch and Kibana appear to be working fine.  However, when I tried to generate a CSV (via **_Reporting -> Generate CSV_**) while on the Discover screen, it fails.  A message dialog appears in the lower right of the browser window with the message:

**Download error
There was an error generating this report.**

If I go to the Reports screen (via **_Reporting -> View Reports_**), I see an entry for the attempt (with a state value of "Created") but clicking on the CSV download link displays a message dialog indicating there was an error.

I found these messages in the Kibana log generated when I made the original request to create the CSV:
```
2020-12-15T18:18:03.585433133Z {"type":"log","@timestamp":"2020-12-15T18:18:03Z","tags":["error","plugins","opendistroReportsKibana"],"pid":1,"message":"Failed to generate report: TypeError: Cannot read property 'settings' of undefined"}
2020-12-15T18:18:03.58643509Z {"type":"log","@timestamp":"2020-12-15T18:18:03Z","tags":["error","plugins","opendistroReportsKibana"],"pid":1,"message":"TypeError: Cannot read property 'settings' of undefined\n    at getMaxResultSize (/usr/share/kibana/plugins/opendistroReportsKibana/server/routes/utils/savedSearchReportHelper.ts:163:35)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
2020-12-15T18:18:03.593793162Z {"type":"error","@timestamp":"2020-12-15T18:18:03Z","tags":[],"pid":1,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toError (/usr/share/kibana/src/core/server/http/router/response_adapter.js:132:19)\n    at HapiResponseAdapter.toHapiResponse (/usr/share/kibana/src/core/server/http/router/response_adapter.js:86:19)\n    at HapiResponseAdapter.handle (/usr/share/kibana/src/core/server/http/router/response_adapter.js:81:17)\n    at Router.handle (/usr/share/kibana/src/core/server/http/router/router.js:164:34)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"?timezone=America/New_York","query":{"timezone":"America/New_York"},"pathname":"/api/reporting/generateReport","path":"/api/reporting/generateReport?timezone=America/New_York","href":"/api/reporting/generateReport?timezone=America/New_York"},"message":"Internal Server Error"}
2020-12-15T18:18:03.593907504Z {"type":"response","@timestamp":"2020-12-15T18:18:03Z","tags":[],"pid":1,"method":"post","statusCode":500,"req":{"url":"/api/reporting/generateReport?timezone=America%2FNew_York","method":"post","headers":{"host":"myserver.com:31033","connection":"keep-alive","content-length":"819","pragma":"no-cache","accept":"*/*","accept-language":"en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,zh-TW;q=0.6","kbn-version":"7.10.0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","content-type":"application/json","origin":"http://myserver.com:31033","referer":"http://myserver.com:31033/app/discover","accept-encoding":"gzip, deflate"},"remoteAddress":"1.1.1.4","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","referer":"http://myserver.com:31033/app/discover"},"res":{"statusCode":500,"responseTime":168,"contentLength":9},"message":"POST /api/reporting/generateReport?timezone=America%2FNew_York 500 168ms - 9.0B"}
```
Please let me know if you need more information.

**Comment by zhongnansu** [comment]
seems similar to this issue https://github.com/opendistro-for-elasticsearch/kibana-reports/issues/249
