### ISSUE TITLE
headless_shell not executable on Mac OS X

### ISSUE THREAD

**Issue by nilei** [opendistro-for-elasticsearch/kibana-reports#281]
the headless shell is not executable in Mac OS X. When trying to download a PDF or PNG, Kibana shows the following messages:

        TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
        
          log   [15:09:54.217] [error][opendistroReportsKibana][plugins] Error: Failed to launch chrome!
        /Users/nils/Downloads/kibana-7.10.0-darwin-x86_64/plugins/opendistroReportsKibana/server/routes/utils/../../../.chromium/headless_shell: /Users/nils/Downloads/kibana-7.10.0-darwin-x86_64/plugins/opendistroReportsKibana/server/routes/utils/../../../.chromium/headless_shell: cannot execute binary file
        
        TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
        
            at onClose (/Users/nils/Downloads/kibana-7.10.0-darwin-x86_64/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/Launcher.js:348:14)
            at Interface.helper.addEventListener (/Users/nils/Downloads/kibana-7.10.0-darwin-x86_64/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/Launcher.js:337:50)
            at Interface.emit (events.js:203:15)
            at Interface.close (readline.js:397:8)
            at Socket.onend (readline.js:173:10)
            at Socket.emit (events.js:203:15)
            at endReadableNT (_stream_readable.js:1145:12)
            at process._tickCallback (internal/process/next_tick.js:63:19)
         error  [15:09:54.188]  Error: Internal Server Error
            at HapiResponseAdapter.toError (/Users/nils/Downloads/kibana-7.10.0-darwin-x86_64/src/core/server/http/router/response_adapter.js:132:19)
            at HapiResponseAdapter.toHapiResponse (/Users/nils/Downloads/kibana-7.10.0-darwin-x86_64/src/core/server/http/router/response_adapter.js:86:19)
            at HapiResponseAdapter.handle (/Users/nils/Downloads/kibana-7.10.0-darwin-x86_64/src/core/server/http/router/response_adapter.js:81:17)
            at Router.handle (/Users/nils/Downloads/kibana-7.10.0-darwin-x86_64/src/core/server/http/router/router.js:164:34)
            at process._tickCallback (internal/process/next_tick.js:68:7)

-- Cheers, Nils

**Comment by zhongnansu** [comment]
@nilei Hi, Are you using the Mac version of headless chromium downloaded from our release page? 
https://github.com/opendistro-for-elasticsearch/kibana-reports/releases/tag/chromium-1.12.0.0

**Comment by nilei** [comment]
@zhongnansu No :-) I missed that in the documentation maybe. How do I use it? Just replace the .chromium directory in the plugins/opendistroReportsKibana directory?

**Comment by zhongnansu** [comment]
Yes, you are right. Give it a try! :wink:
