### ISSUE TITLE
Report generating points to localhost instead of Kibana Server

### ISSUE THREAD

**Issue by alessiocreo** [opendistro-for-elasticsearch/kibana-reports#308]
Hi,

I've installed Kibana report plugin 1.12 on elasticsearch-oss-7.10.0 and kibana-oss-7.10.0. 

```  log   [19:54:04.153] [info][listening] Server running at http://192.168.1.82:8080
  log   [19:54:04.242] [info][server][Kibana][http] http server running at http://192.168.1.82:8080
  log   [19:55:38.143] [error][data][elasticsearch] [version_conflict_engine_exception]: [search-telemetry:search-telemetry]: version conflict, required seqNo [26], primary term [1]. current document has seqNo [27] and primary term [1]
  log   [19:55:38.527] [error][data][elasticsearch] [version_conflict_engine_exception]: [search-telemetry:search-telemetry]: version conflict, required seqNo [33], primary term [1]. current document has seqNo [34] and primary term [1]
  log   [19:55:42.636] [info][opendistroReportsKibana][plugins] domain enables security, use session cookie to access
  log   [19:55:42.808] [info][opendistroReportsKibana][plugins] original queryUrl http://localhost:5601/app/dashboards#/view/722b74f0-b882-11e8-a6d9-e546fe2bba5f?_g=(filters:!(),refreshInterval:(pause:!f,value:900000),time:(from:'2021-01-20T19:55:42.048Z',to:'2021-01-27T19:55:42.048Z'))&_a=(description:'Analyze%20mock%20eCommerce%20orders%20and%20revenue',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'%5BeCommerce%5D%20Revenue%20Dashboard',viewMode:view)
  log   [19:55:42.836] [error][opendistroReportsKibana][plugins] Failed to generate report: Error: net::ERR_CONNECTION_REFUSED at http://localhost:5601/app/dashboards#/view/722b74f0-b882-11e8-a6d9-e546fe2bba5f?_g=(filters:!(),refreshInterval:(pause:!f,value:900000),time:(from:'2021-01-20T19:55:42.048Z',to:'2021-01-27T19:55:42.048Z'))&_a=(description:'Analyze%20mock%20eCommerce%20orders%20and%20revenue',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'%5BeCommerce%5D%20Revenue%20Dashboard',viewMode:view)
  log   [19:55:42.836] [error][opendistroReportsKibana][plugins] Error: net::ERR_CONNECTION_REFUSED at http://localhost:5601/app/dashboards#/view/722b74f0-b882-11e8-a6d9-e546fe2bba5f?_g=(filters:!(),refreshInterval:(pause:!f,value:900000),time:(from:'2021-01-20T19:55:42.048Z',to:'2021-01-27T19:55:42.048Z'))&_a=(description:'Analyze%20mock%20eCommerce%20orders%20and%20revenue',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'%5BeCommerce%5D%20Revenue%20Dashboard',viewMode:view)
    at navigate (/elastic/OD/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/FrameManager.js:120:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/elastic/OD/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/helper.js:111:15)
    at Page.goto (/elastic/OD/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/Page.js:674:49)
    at Page.goto (/elastic/OD/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/helper.js:112:23)
    at createVisualReport (/elastic/OD/kibana/plugins/opendistroReportsKibana/server/routes/utils/visual_report/visualReportHelper.ts:83:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 error  [19:55:41.685]  Error: Internal Server Error
    at HapiResponseAdapter.toError (/elastic/OD/kibana/src/core/server/http/router/response_adapter.js:132:19)
    at HapiResponseAdapter.toHapiResponse (/elastic/OD/kibana/src/core/server/http/router/response_adapter.js:86:19)
    at HapiResponseAdapter.handle (/elastic/OD/kibana/src/core/server/http/router/response_adapter.js:81:17)
    at Router.handle (/elastic/OD/kibana/src/core/server/http/router/router.js:164:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  log   [19:55:43.790] [error][data][elasticsearch] [illegal_argument_exception]: request [/_license] contains unrecognized parameter: [accept_enterprise]
  log   [19:59:04.260] [error][data][elasticsearch] [illegal_argument_exception]: request [/_license] contains unrecognized parameter: [accept_enterprise]
  log   [19:59:24.241] [error][data][elasticsearch] [version_conflict_engine_exception]: [search-telemetry:search-telemetry]: version conflict, required seqNo [85], primary term [1]. current document has seqNo [86] and primary term [1]
  log   [19:59:31.710] [info][opendistroReportsKibana][plugins] domain enables security, use session cookie to access
  log   [19:59:31.881] [info][opendistroReportsKibana][plugins] original queryUrl http://localhost:5601/app/dashboards#/view/722b74f0-b882-11e8-a6d9-e546fe2bba5f?_g=(filters:!(),refreshInterval:(pause:!f,value:900000),time:(from:'2021-01-20T19:59:31.644Z',to:'2021-01-27T19:59:31.644Z'))&_a=(description:'Analyze%20mock%20eCommerce%20orders%20and%20revenue',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'%5BeCommerce%5D%20Revenue%20Dashboard',viewMode:view)
  log   [19:59:31.899] [error][opendistroReportsKibana][plugins] Failed to generate report: Error: net::ERR_CONNECTION_REFUSED at http://localhost:5601/app/dashboards#/view/722b74f0-b882-11e8-a6d9-e546fe2bba5f?_g=(filters:!(),refreshInterval:(pause:!f,value:900000),time:(from:'2021-01-20T19:59:31.644Z',to:'2021-01-27T19:59:31.644Z'))&_a=(description:'Analyze%20mock%20eCommerce%20orders%20and%20revenue',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'%5BeCommerce%5D%20Revenue%20Dashboard',viewMode:view)
```

as you can see I've set my Kibana server published on 192.168.1.82:8080but when I try to generate a report the logs say that he's trying to connect to localhost:5601.

The configuration of security plugin and the report plugin are the default.

Can anyone help?

Thanks a lot,
Alessio

**Comment by zhongnansu** [comment]
Hi, I believe this is a known issue with upstream Kibana new plugin platform, that plugins are unable to read all configurations from `kibana.yml`. We are tracking it in issue #98 and working on alternative solutions.

Thanks

**Comment by zhongnansu** [comment]
close this one, since we are tracking this issue on #98
