### ISSUE TITLE
500 error while downloading reports in kibana

### ISSUE THREAD

**Issue by sushovan23** [opendistro-for-elasticsearch/kibana-reports#386]
Version details:
elasticsearch-oss-7.10.2-1.x86_64
opendistroforelasticsearch-1.13.1-1.x86_64
opendistroforelasticsearch-kibana-1.13.1-1.x86_64

How to reproduce:
While trying to download reports in kibana getting following error:
`Jul 14 14:50:47 hostname kibana[10656]: {"type":"log","@timestamp":"2021-07-14T14:50:47Z","tags":["error","plugins","opendistroReportsKibana"],"pid":10656,"message":"Failed to generate report: [object Object]"}
Jul 14 14:50:47 hostname kibana[10656]: {"type":"log","@timestamp":"2021-07-14T14:50:47Z","tags":["error","plugins","opendistroReportsKibana"],"pid":10656,"message":"ErrorEvent {\n  target:\n   WebSocket {\n     _events:\n      [Object: null prototype] { open: [Function], error: [Function] },\n     _eventsCount: 2,\n     _maxListeners: undefined,\n     readyState: 3,\n     protocol: '',\n     _binaryType: 'nodebuffer',\n     _closeFrameReceived: false,\n     _closeFrameSent: false,\n     _closeMessage: '',\n     _closeTimer: null,\n     _closeCode: 1006,\n     _extensions: {},\n     _receiver: null,\n     _sender: null,\n     _socket: null,\n     _isServer: false,\n     _redirects: 0,\n     url:\n      'ws://127.0.0.1:51353/devtools/browser/6313a14f-bb42-4bca-a9a1-85cde5400ff2',\n     _req: null },\n  type: 'error',\n  message: 'socket hang up',\n  error:\n   { Error: socket hang up\n       at createHangUpError (_http_client.js:332:15)\n       at Socket.socketOnEnd (_http_client.js:435:23)\n       at Socket.emit (events.js:203:15)\n       at endReadableNT (_stream_readable.js:1145:12)\n       at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' } }"}
Jul 14 14:50:47 hostname kibana[10656]: {"type":"error","@timestamp":"2021-07-14T14:50:46Z","tags":[],"pid":10656,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toError (/usr/share/kibana/src/core/server/http/router/response_adapter.js:132:19)\n    at HapiResponseAdapter.toHapiResponse (/usr/share/kibana/src/core/server/http/router/response_adapter.js:86:19)\n    at HapiResponseAdapter.handle (/usr/share/kibana/src/core/server/http/router/response_adapter.js:81:17)\n    at Router.handle (/usr/share/kibana/src/core/server/http/router/router.js:164:34)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"?timezone=America/New_York","query":{"timezone":"America/New_York"},"pathname":"/api/reporting/generateReport","path":"/api/reporting/generateReport?timezone=America/New_York","href":"/api/reporting/generateReport?timezone=America/New_York"},"message":"Internal Server Error"}
Jul 14 14:50:47 hostname kibana[10656]: {"type":"response","@timestamp":"2021-07-14T14:50:46Z","tags":[],"pid":10656,"method":"post","statusCode":500,"req":{"url":"/api/reporting/generateReport?timezone=America%2FNew_York","method":"post","headers":{"host":"127.0.0.1:5601","sec-ch-ua":"\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"","pragma":"no-cache","accept-language":"en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,zh-TW;q=0.6","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36","content-type":"application/json","accept":"*/*","kbn-version":"7.10.2","origin":"https://kibana-url","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://kibana-url/app/dashboards","accept-encoding":"gzip, deflate, br","x-forwarded-for":"10.166.49.109","x-forwarded-host":"kibana-server","x-forwarded-server":"kibana-server","connection":"Keep-Alive","content-length":"898","securitytenant":""},"remoteAddress":"127.0.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36","referer":"https://kibana-url/app/dashboards"},"res":{"statusCode":500,"responseTime":259,"contentLength":9},"message":"POST /api/reporting/generateReport?timezone=America%2FNew_York 500 259ms - 9.0B"}`

Let me know if there is any settings in kibana.yml which I would need to apply to overcome this error?

**Comment by zhongnansu** [comment]
Maybe this can help?
https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/reporting/#troubleshooting
