### ISSUE TITLE
Timeout when I try to download PDF from Reporting Module

### ISSUE THREAD

**Issue by alejandroorg** [opendistro-for-elasticsearch/kibana-reports#391]
Hello,

I have a problem when I try to download anything from the reporting module. Is not related to the amount of data because I have tried that with a visualization with 6 events or with 30 millions of events.

Those logs are an example of the errors I get while I'm trying to download the PDF:
 
```
Aug  6 21:32:59 elasticsearch-master kibana[68035]: {"type":"error","@timestamp":"2021-08-06T13:32:59Z","tags":["warning","process"],"pid":68035,"level":"error","error":{"message":"Possible EventEmitter memory leak detected. 11 SIGHUP listeners added. Use emitter.setMaxListeners() to increase limit","name":"MaxListenersExceededWarning","stack":"MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGHUP listeners added. Use emitter.setMaxListeners() to increase limit\n    at _addListener (events.js:256:17)\n    at process.addListener (events.js:272:10)\n    at Function.addEventListener (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/helper.js:130:13)\n    at Launcher.launch (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/Launcher.js:171:29)"},"message":"Possible EventEmitter memory leak detected. 11 SIGHUP listeners added. Use emitter.setMaxListeners() to increase limit"}
Aug  6 21:35:10 elasticsearch-master kibana[68035]: {"type":"log","@timestamp":"2021-08-06T13:35:10Z","tags":["error","plugins","opendistroReportsKibana"],"pid":68035,"message":"Failed to generate report: Error: net::ERR_CONNECTION_TIMED_OUT at https://x.x.x.x:443/app/dashboards#/view/366fa430-ce6f-11eb-8f08-fb1673d1a2b8?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:''2021-06-30T16:00:00.000Z'',to:'2021-07-31T15:30:00.000Z'))&_a=(description:'366fa430-ce6f-11eb-8f08-fb1673d1a2b8',filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'wazuh-alerts-*',key:data.devid,negate:!f,params:(query:FGT60FTK20089749),type:phrase),query:(match_phrase:(data.devid:FGT60FTK20089749))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'wazuh-alerts-*',key:rule.level,negate:!f,params:(gte:12,lt:20),type:range),range:(rule.level:(gte:12,lt:20)))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'YC%20Capital%20Dashboard',viewMode:view)"}
Aug  6 21:35:10 elasticsearch-master kibana[68035]: {"type":"log","@timestamp":"2021-08-06T13:35:10Z","tags":["error","plugins","opendistroReportsKibana"],"pid":68035,"message":"Error: net::ERR_CONNECTION_TIMED_OUT at https://x.x.x.x:443/app/dashboards#/view/366fa430-ce6f-11eb-8f08-fb1673d1a2b8?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:''2021-06-30T16:00:00.000Z'',to:'2021-07-31T15:30:00.000Z'))&_a=(description:'366fa430-ce6f-11eb-8f08-fb1673d1a2b8',filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'wazuh-alerts-*',key:data.devid,negate:!f,params:(query:FGT60FTK20089749),type:phrase),query:(match_phrase:(data.devid:FGT60FTK20089749))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'wazuh-alerts-*',key:rule.level,negate:!f,params:(gte:12,lt:20),type:range),range:(rule.level:(gte:12,lt:20)))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'YC%20Capital%20Dashboard',viewMode:view)\n    at navigate (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/FrameManager.js:120:37)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/helper.js:111:15)\n    at Page.goto (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/Page.js:674:49)\n    at Page.goto (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/helper.js:112:23)\n    at createVisualReport (/usr/share/kibana/plugins/opendistroReportsKibana/server/routes/utils/visual_report/visualReportHelper.ts:91:14)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
Aug  6 21:41:05 elasticsearch-master kibana[68035]: {"type":"error","@timestamp":"2021-08-06T13:41:05Z","tags":["warning","process"],"pid":68035,"level":"error","error":{"message":"Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit","name":"MaxListenersExceededWarning","stack":"MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit\n    at _addListener (events.js:256:17)\n    at process.addListener (events.js:272:10)\n    at Function.addEventListener (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/helper.js:130:13)\n    at Launcher.launch (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/Launcher.js:165:32)"},"message":"Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit"}
Aug  6 21:43:14 elasticsearch-master kibana[68035]: {"type":"log","@timestamp":"2021-08-06T13:43:14Z","tags":["error","plugins","opendistroReportsKibana"],"pid":68035,"message":"Failed to generate report: Error: net::ERR_CONNECTION_TIMED_OUT at https://x.x.x.x:443/app/dashboards#/view/ef3b4bd0-f6bb-11eb-b830-398fd0a8da3f?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-05T13:41:05.456Z',to:'2021-08-06T13:41:05.456Z'))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!f,title:'Device%20events%20-%20Testing',viewMode:view)"}


Aug  6 22:04:44 elasticsearch-master kibana[118122]: {"type":"log","@timestamp":"2021-08-06T14:04:44Z","tags":["error","plugins","opendistroReportsKibana"],"pid":118122,"message":"Error: net::ERR_CONNECTION_TIMED_OUT at https://x.x.x.x:443/app/dashboards#/view/ef3b4bd0-f6bb-11eb-b830-398fd0a8da3f?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-05T14:02:33.498Z',to:'2021-08-06T14:02:33.498Z'))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!f,title:'Device%20events%20-%20Testing',viewMode:view)\n    at navigate (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/FrameManager.js:120:37)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/helper.js:111:15)\n    at Page.goto (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/Page.js:674:49)\n    at Page.goto (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/helper.js:112:23)\n    at createVisualReport (/usr/share/kibana/plugins/opendistroReportsKibana/server/routes/utils/visual_report/visualReportHelper.ts:91:14)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
Aug  6 22:06:47 elasticsearch-master kibana[118122]: {"type":"log","@timestamp":"2021-08-06T14:06:47Z","tags":["error","elasticsearch","data"],"pid":118122,"message":"[illegal_argument_exception]: request [/_license] contains unrecognized parameter: [accept_enterprise]"}
Aug  6 22:06:55 elasticsearch-master kibana[118122]: {"type":"log","@timestamp":"2021-08-06T14:06:55Z","tags":["error","plugins","opendistroReportsKibana"],"pid":118122,"message":"Failed to generate report: Error: net::ERR_CONNECTION_TIMED_OUT at https://x.x.x.x:443/app/dashboards#/view/ef3b4bd0-f6bb-11eb-b830-398fd0a8da3f?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-05T14:02:33.498Z',to:'2021-08-06T14:02:33.498Z'))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!f,title:'Device%20events%20-%20Testing',viewMode:view)"}
Aug  6 22:06:55 elasticsearch-master kibana[118122]: {"type":"log","@timestamp":"2021-08-06T14:06:55Z","tags":["error","plugins","opendistroReportsKibana"],"pid":118122,"message":"Error: net::ERR_CONNECTION_TIMED_OUT at https://x.x.x.x:443/app/dashboards#/view/ef3b4bd0-f6bb-11eb-b830-398fd0a8da3f?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-05T14:02:33.498Z',to:'2021-08-06T14:02:33.498Z'))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!f,title:'Device%20events%20-%20Testing',viewMode:view)\n    at navigate (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/FrameManager.js:120:37)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/helper.js:111:15)\n    at Page.goto (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/Page.js:674:49)\n    at Page.goto (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/helper.js:112:23)\n    at createVisualReport (/usr/share/kibana/plugins/opendistroReportsKibana/server/routes/utils/visual_report/visualReportHelper.ts:91:14)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
Aug  6 22:09:06 elasticsearch-master kibana[118122]: {"type":"log","@timestamp":"2021-08-06T14:09:06Z","tags":["error","plugins","opendistroReportsKibana"],"pid":118122,"message":"Failed to generate report: Error: net::ERR_CONNECTION_TIMED_OUT at https://x.x.x.x:443/app/dashboards#/view/ef3b4bd0-f6bb-11eb-b830-398fd0a8da3f?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-05T14:06:08.465Z',to:'2021-08-06T14:06:08.465Z'))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!f,title:'Device%20events%20-%20Testing',viewMode:view)"}
Aug  6 22:09:06 elasticsearch-master kibana[118122]: {"type":"log","@timestamp":"2021-08-06T14:09:06Z","tags":["error","plugins","opendistroReportsKibana"],"pid":118122,"message":"Error: net::ERR_CONNECTION_TIMED_OUT at https://x.x.x.x:443/app/dashboards#/view/ef3b4bd0-f6bb-11eb-b830-398fd0a8da3f?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-05T14:06:08.465Z',to:'2021-08-06T14:06:08.465Z'))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!f,title:'Device%20events%20-%20Testing',viewMode:view)\n    at navigate (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/FrameManager.js:120:37)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/helper.js:111:15)\n    at Page.goto (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/Page.js:674:49)\n    at Page.goto (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/helper.js:112:23)\n    at createVisualReport (/usr/share/kibana/plugins/opendistroReportsKibana/server/routes/utils/visual_report/visualReportHelper.ts:91:14)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}

```

How can I fix it?

**Comment by rsmeyers** [comment]
Hitting same issue on opendistroforelasticsearch-kibana-1.13.2-1.x86_64 when generating report

Sep  9 10:06:02 trapr-01 kibana[2461604]: {"type":"response","@timestamp":"2021-09-09T08:03:47Z","tags":[],"pid":2461604,"method":"post","statusCode":200,"req":{"url":"/
api/reporting/generateReport?timezone=Europe%2FBerlin","method":"post","headers":{"host":"127.0.0.1:5601","sec-ch-ua":"\"Google Chrome\";v=\"93\", \" Not;A Brand\";v=\"9
9\", \"Chromium\";v=\"93\"","pragma":"no-cache","accept-language":"en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,zh-TW;q=0.6","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36","content-type":"application/json","accept":"*/*","kbn-version":"7.10
.2","sec-ch-ua-platform":"\"Windows\"","origin":"https://trapr.cisco.com","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"http
s://trapr.cisco.com/kibana/app/dashboards","accept-encoding":"gzip, deflate, br","x-forwarded-for":"10.55.17.86","x-forwarded-host":"trapr.cisco.com","x-forwarded-server
":"trapr.cisco.com","connection":"Keep-Alive","content-length":"902","securitytenant":"trapr_aci"},"remoteAddress":"127.0.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0;
 Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36","referer":"https://trapr.cisco.com/kibana/app/dashboards"},"res":{"statusCode":200
,"responseTime":134431,"contentLength":9},"message":"POST /api/reporting/generateReport?timezone=Europe%2FBerlin 200 134431ms - 9.0B"}
Sep  9 10:06:02 trapr-01 kibana[2461604]: {"type":"error","@timestamp":"2021-09-09T08:06:02Z","tags":["warning","process"],"pid":2461604,"level":"error","error":{"messag
e":"Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit","name":"MaxListenersExceededWarning","stack":"M
axListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit\n    at _addListener (ev
ents.js:256:17)\n    at process.addListener (events.js:272:10)\n    at Function.addEventListener (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppetee
r-core/lib/helper.js:130:13)\n    at Launcher.launch (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/Launcher.js:165:32)"},"message":"
Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit"}

**Comment by rsmeyers** [comment]
Hitting same issue on opendistroforelasticsearch-kibana-1.13.2-1.x86_64
Sep  9 10:06:02 blah-01 kibana[2461604]: {"type":"response","@timestamp":"2021-09-09T08:03:47Z","tags":[],"pid":2461604,"method":"post","statusCode":200,"req":{"url":"/
api/reporting/generateReport?timezone=Europe%2FBerlin","method":"post","headers":{"host":"127.0.0.1:5601","sec-ch-ua":"\"Google Chrome\";v=\"93\", \" Not;A Brand\";v=\"9
9\", \"Chromium\";v=\"93\"","pragma":"no-cache","accept-language":"en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,zh-TW;q=0.6","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36","content-type":"application/json","accept":"*/*","kbn-version":"7.10
.2","sec-ch-ua-platform":"\"Windows\"","origin":"https://blah.com","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"http
s://blah.com/kibana/app/dashboards","accept-encoding":"gzip, deflate, br","x-forwarded-for":"10.55.17.86","x-forwarded-host":"blah.com","x-forwarded-server
":"blah.com","connection":"Keep-Alive","content-length":"902","securitytenant":"blah"},"remoteAddress":"127.0.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0;
 Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36","referer":"https://blah.com/kibana/app/dashboards"},"res":{"statusCode":200
,"responseTime":134431,"contentLength":9},"message":"POST /api/reporting/generateReport?timezone=Europe%2FBerlin 200 134431ms - 9.0B"}
Sep  9 10:06:02 blah-01 kibana[2461604]: {"type":"error","@timestamp":"2021-09-09T08:06:02Z","tags":["warning","process"],"pid":2461604,"level":"error","error":{"messag
e":"Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit","name":"MaxListenersExceededWarning","stack":"M
axListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit\n    at _addListener (ev
ents.js:256:17)\n    at process.addListener (events.js:272:10)\n    at Function.addEventListener (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppetee
r-core/lib/helper.js:130:13)\n    at Launcher.launch (/usr/share/kibana/plugins/opendistroReportsKibana/node_modules/puppeteer-core/lib/Launcher.js:165:32)"},"message":"
Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit"}
