### ISSUE TITLE
Missing plugin [opendistro-job-scheduler] dependency of [opendistro-reports-scheduler]

### ISSUE THREAD

**Issue by zhongnansu** [opendistro-for-elasticsearch/kibana-reports#66]
```
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Missing plugin [opendistro-job-scheduler], dependency of [opendistro-reports-scheduler]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:174) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127) ~[elasticsearch-cli-7.8.0.jar:7.8.0]
```

After manually built the OD job-scheduler artifact and add it to the ES plugin folder, along with the reports-scheduler, it will work.

**Comment by zhongnansu** [comment]
This is not a bug. User have to manually install job-scheduler plugin, for reports-scheduler plugin to run successfully. But Need to add to the development guide.
